<?php

namespace Drupal\Tests\blog\Kernel;

use Drupal\blog\Repository\ArticleRepository;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\KernelTests\Core\Entity\EntityKernelTestBase;
use Drupal\node\NodeInterface;
use Drupal\Tests\node\Traits\NodeCreationTrait;

class ArticleRepositoryTest extends EntityKernelTestBase {

  use NodeCreationTrait;

  public static $modules = [
    'node',
    'blog',
  ];

  protected function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub

    $this->installConfig(['filter']);
  }

  /** @test */
  public function only_articles_are_returned() {
    // arrange
    $repo = $this->container->get(ArticleRepository::class);
    $this->createNode(['type' => 'article']);
    $this->createNode(['type' => 'page']);
    $this->createNode(['type' => 'article']);
    $this->createNode(['type' => 'page']);
    $this->createNode(['type' => 'article']);

    // act
    $articles = $repo->getAll();

    // assert
    $this->assertCount(3, $articles);
  }

  /** @test */
  public function only_published_articles_are_returned() {
    // arrange
    $repo = $this->container->get(ArticleRepository::class);
    $this->createNode(['type' => 'article', 'status' => NodeInterface::PUBLISHED]);
    $this->createNode(['type' => 'article', 'status' => NodeInterface::NOT_PUBLISHED]);
    $this->createNode(['type' => 'article', 'status' => NodeInterface::PUBLISHED]);
    $this->createNode(['type' => 'article', 'status' => NodeInterface::NOT_PUBLISHED]);
    $this->createNode(['type' => 'article', 'status' => NodeInterface::PUBLISHED]);

    // act
    $articles = $repo->getAll();

    // assert
    $this->assertCount(3, $articles);
  }

  /** @test */
  public function articles_are_returned_in_the_correct_order() {
    $this->createNode(['type' => 'article', 'created' => (new DrupalDateTime('-2 days'))->getTimestamp()]);
    $this->createNode(['type' => 'article', 'created' => (new DrupalDateTime('-1 week'))->getTimestamp()]);
    $this->createNode(['type' => 'article', 'created' => (new DrupalDateTime('-1 hour'))->getTimestamp()]);
    $this->createNode(['type' => 'article', 'created' => (new DrupalDateTime('-1 year'))->getTimestamp()]);
    $this->createNode(['type' => 'article', 'created' => (new DrupalDateTime('-1 month'))->getTimestamp()]);

    $repository = $this->container->get(ArticleRepository::class);
    $nodes = $repository->getAll();
    $nodeIds = array_keys($nodes);

    $this->assertSame([3, 1, 2, 5, 4], $nodeIds);
  }


}
